name: Deploy to PyPI

on:
  push:
    branches:
    - master

jobs:
  - name: Deploy package
    uses: remorses/pypi@master
    with:
      setupfile: ./setup.py
      username: ${{ secrets.pypi_username }}
      password: ${{ secrets.pypi_password }}
